export interface WordEntry {
  id: number;
  arabic: string;
  audio: string;
  /**
   * Letter-boundary times in seconds: length = letterCount + 1.
   * boundaries[i] is when letter i begins; the last entry is when speech ends.
   * null = not calibrated; the app computes timings automatically from the audio.
   * Generated by the calibration page — never hand-typed.
   */
  timings: number[] | null;
}

export interface Lesson {
  lesson: number;
  title: string;
  titleArabic: string;
  /** Path (relative to the site root) of this lesson's audio folder. */
  audioPath: string;
  words: WordEntry[];
}
